name: Deploy TypeScript App

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: eslint
        run: pnpm lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-node@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Build
        run: pnpm build

  check-version:
    name: Version Check
    runs-on: ubuntu-latest
    needs: build

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      # The fetch-depth and fetch-tags options are required
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4

      - name: Check Version
        id: check-version
        uses: issue-ops/semver@v1.2.0
        with:
          check-only: true
          manifest-path: ${{ env.MANIFEST_PATH }}

      - name: Print version
        run: echo ${{ steps.check-version.outputs.version }}

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Publish release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_REPOSITORY: ${{ github.repository }}
  #       run: gh release edit "v${{ steps.version.outputs.version }}" --draft=false
