name: Deploy Lamba Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create archive
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-archive
          path: ${{ github.sha }}.zip