name: Deploy Lamba Function

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install flake8
        run: pip install flake8
      - name: Lint
        run: |
          cd function
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create archive
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-archive
          path: ${{ github.sha }}.zip

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: zipped-archive
          tag: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: Release ${{ github.sha }}.
          draft: false
          prerelease: false
