name: Publish

on: 
  push:
    branches:
      - 'dev'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          # run_install: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Configure git
        run: |
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
      - name: Bump version
        run: pnpm version patch -m "[ci skip] Automated version bump to %s"
      - name: Extract version
        uses: issue-ops/semver@v1.2.0
        id: extract-version
        with:
          manifest-path: package.json
      - name: Print version
        run: echo ${{ steps.extract-version.outputs.version }}