name: Publish

on: 
  push:
    branches:
      - 'dev'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          # run_install: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Configure git
        run: |
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}@users.noreply.github.com
      - name: check version and tags
        run: |
            grep "version" package.json
            git tag -l
            git ls-remote --tags
            # pnpm version patch -m "[ci skip] Automated version bump to %s"
            
      - name: Release
        run: pnpm release
      - name: git status
        run: |
          git status
          git tag -l
          git ls-remote --tags
      - name: Extract version
        uses: issue-ops/semver@v1.2.0
        id: extract-version
        with:
          manifest-path: package.json
          overwrite: true
      - name: Print version
        run: echo ${{ steps.extract-version.outputs.version }}
      - name: Check status for v${{ steps.extract-version.outputs.version }}
        # run: gh release create v${{ steps.extract-version.outputs.version }} -t v${{ steps.extract-version.outputs.version }} -n "Release v${{ steps.extract-version.outputs.version }}"
        run: git status